const facilityData = [
  {
    id: 1,
    name: 'TF 복싱짐',
    item_nm: '복싱',
    location: '서울',
    address: '서울특별시 종로구 세종대로 175',
  },
  {
    id: 2,
    name: '태권브이',
    item_nm: '태권도',
    location: '서울',
    address: '서울특별시 강남구 테헤란로 123',
  },
  {
    id: 3,
    name: '헬스킹짐',
    item_nm: '헬스',
    location: '서울',
    address: '서울특별시 송파구 올림픽로 300',
  },
  {
    id: 4,
    name: '서울 요가 스튜디오',
    item_nm: '요가',
    location: '서울',
    address: '서울특별시 마포구 양화로 188',
  },
  {
    id: 5,
    name: '스위밍 플러스',
    item_nm: '수영',
    location: '서울',
    address: '서울특별시 서초구 사임당로 17',
  },
  {
    id: 6,
    name: '럭키 테니스 코트',
    item_nm: '테니스',
    location: '서울',
    address: '서울특별시 성동구 왕십리로 410',
  },
  {
    id: 7,
    name: '강북 클라이밍 센터',
    item_nm: '클라이밍',
    location: '서울',
    address: '서울특별시 강북구 한천로 112',
  },
  {
    id: 8,
    name: '이너피스 필라테스',
    item_nm: '필라테스',
    location: '서울',
    address: '서울특별시 동작구 동작대로 145',
  },
  {
    id: 9,
    name: '서울 양궁장',
    item_nm: '양궁',
    location: '서울',
    address: '서울특별시 중랑구 면목로 370',
  },
  {
    id: 10,
    name: '스파이더 피트니스',
    item_nm: '크로스핏',
    location: '서울',
    address: '서울특별시 광진구 능동로 90',
  },
  {
    id: 11,
    name: '디펜스 유도 도장',
    item_nm: '유도',
    location: '서울',
    address: '서울특별시 용산구 이태원로 45',
  },
  {
    id: 12,
    name: '왕십리 볼링장',
    item_nm: '볼링',
    location: '서울',
    address: '서울특별시 성동구 왕십리로 85',
  },
  {
    id: 13,
    name: '강서 족구장',
    item_nm: '족구',
    location: '서울',
    address: '서울특별시 강서구 화곡로 266',
  },
  {
    id: 14,
    name: '빅웨이브 서핑',
    item_nm: '서핑',
    location: '서울',
    address: '서울특별시 은평구 불광로 320',
  },
  {
    id: 15,
    name: '정글 피트니스',
    item_nm: '피트니스',
    location: '서울',
    address: '서울특별시 관악구 관악로 199',
  },
  {
    id: 16,
    name: '강동 파크골프장',
    item_nm: '파크골프',
    location: '서울',
    address: '서울특별시 강동구 고덕로 123',
  },
  {
    id: 17,
    name: '올림픽 테니스 코트',
    item_nm: '테니스',
    location: '서울',
    address: '서울특별시 송파구 방이동 88',
  },
  {
    id: 18,
    name: '청계천 자전거 대여소',
    item_nm: '자전거',
    location: '서울',
    address: '서울특별시 종로구 창신동 1',
  },
  {
    id: 19,
    name: '광진구 배드민턴장',
    item_nm: '배드민턴',
    location: '서울',
    address: '서울특별시 광진구 자양동 136-30',
  },
  {
    id: 20,
    name: '서초 스쿼시 클럽',
    item_nm: '스쿼시',
    location: '서울',
    address: '서울특별시 서초구 서초대로 89',
  },
];

export default facilityData;
